begin;
create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, auth;
select plan(10);
insert into auth.users(id,email) values ('b7777777-7777-4777-8777-777777777777','feedback@example.test');
select ok(not has_table_privilege('authenticated','public.activity_logs','INSERT'), 'retired activity writes denied');
select ok(not has_table_privilege('authenticated','public.feedback_reports','INSERT'), 'direct feedback writes denied');
select ok(not exists(select 1 from pg_policies where schemaname='storage' and policyname='feedback screenshots: upload own'), 'screenshot upload policy removed');
select ok(not has_function_privilege('anon','public.submit_feedback(text,text)','EXECUTE'), 'anonymous role cannot submit');
set local role authenticated;
select set_config('request.jwt.claim.sub','b7777777-7777-4777-8777-777777777777',true);
select throws_ok($$select public.submit_feedback('bug',repeat('x',8193))$$,'22023','invalid_feedback','oversized text rejected');
select throws_ok($$select public.submit_feedback('bug',' ')$$,'22023','invalid_feedback','empty text rejected');
select lives_ok($$select public.submit_feedback('bug','valid')$$,'valid report accepted');
reset role;
select ok((select screenshot_path is null and device is null from public.feedback_reports where user_id='b7777777-7777-4777-8777-777777777777'), 'new report contains only text');
insert into public.feedback_reports(user_id,context_tag,description) select 'b7777777-7777-4777-8777-777777777777','bug','filler' from generate_series(1,4);
set local role authenticated;
select throws_ok($$select public.submit_feedback('bug','x')$$,'P0001','feedback_quota_exceeded','hourly limit');
reset role;
update public.feedback_reports set created_at=now()-interval '2 hours' where user_id='b7777777-7777-4777-8777-777777777777';
insert into public.feedback_reports(user_id,context_tag,description,created_at) select 'b7777777-7777-4777-8777-777777777777','bug','filler',now()-interval '2 hours' from generate_series(1,95);
set local role authenticated;
select throws_ok($$select public.submit_feedback('bug','x')$$,'P0001','feedback_quota_exceeded','retained row limit');
reset role;
select * from finish();
rollback;
