// node supabase/tests/member_location_sync.mjs <path-to-pglite/dist/index.js>
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(pathToFileURL(resolve(process.argv[2])).href);
const db = new PGlite();
const read = file => readFileSync(new URL(`../migrations/${file}`, import.meta.url), 'utf8');
await db.exec(`create role anon; create role authenticated; create schema auth; create schema extensions;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
grant usage on schema public, auth, extensions to authenticated;
`);
const initial=read('20260617000000_supabase_init.sql');
await db.exec(initial.slice(0, initial.indexOf('-- profiles ---')));
const navigation=read('20260716214247_team_navigation_sessions.sql');
await db.exec(navigation.slice(0,navigation.indexOf('create table public.diagnostic_sessions')));
await db.exec(`create table public.subgroups(id uuid,group_id uuid);
create table public.core_entity_versions(group_id uuid,entity_type text,entity_id uuid,entity_version bigint,updated_at timestamptz,state jsonb);
create table public.location_refresh_requests(group_id uuid primary key,requested_by uuid,requested_at timestamptz);
create function public.anonymous_access_is_active(uuid) returns boolean language sql as $$ select true $$;
create function extensions.notify_push(jsonb) returns void language sql as $$ select $$;
grant select,insert,update on public.member_locations, public.location_upload_events, public.member_privacy_settings to authenticated;
grant select on public.memberships,public.navigation_sessions to authenticated;
create policy member_read on public.memberships for select to authenticated using(extensions.is_member(group_id));
create policy location_read on public.member_locations for select to authenticated using(extensions.is_member(group_id));
create policy location_insert on public.member_locations for insert to authenticated with check(user_id=auth.uid() and extensions.is_member(group_id));
create policy location_update on public.member_locations for update to authenticated using(user_id=auth.uid() and extensions.is_member(group_id)) with check(user_id=auth.uid() and extensions.is_member(group_id));
alter table public.location_upload_events enable row level security;
create policy event_read on public.location_upload_events for select to authenticated using(user_id=auth.uid());
create policy event_insert on public.location_upload_events for insert to authenticated with check(user_id=auth.uid() and extensions.is_member(group_id));
alter table public.member_privacy_settings enable row level security;
create policy privacy_own on public.member_privacy_settings for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
`);
await db.exec(read('20260813100000_location_refresh_pending.sql'));
await db.exec(read('20260929164531_reliable_member_location_sync.sql'));
await db.exec(read('20260929173500_location_rejection_idempotency.sql'));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
for(let i=1;i<=6;i++) await db.query('insert into auth.users values($1)',[id(i)]);
for(const g of [100,200]) await db.query("insert into groups(id,name,invite_code) values($1,$2,$2)",[id(g),`D${g}`]);
for(let i=1;i<=6;i++) await db.query('insert into memberships(group_id,user_id,role) values($1,$2,$3)',[id(i<=4?100:200),id(i),i===1||i===5?'leader':'follower']);
await db.exec('set role authenticated');
const uid=async n=>db.query("select set_config('test.uid',$1,false)",[id(n)]);
const rpc=async (name,args=[]) => (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
let sequence=1000;
const event=(group=100,time=Date.now(),lat=25)=>({id:id(++sequence),groupId:id(group),navigationSessionId:null,capturedAt:time,coords:{latitude:lat,longitude:121,accuracy:5},trackingMode:'foreground',source:'foreground',sequence});
for(let i=1;i<=6;i++) { await uid(i); const e=event(i<=4?100:200); assert.deepEqual((await rpc('ingest_location_batch',[JSON.stringify([e])])).acceptedIds,[e.id]); }
await uid(1);
const snapshot=await rpc('get_group_recovery_snapshot',[id(100)]); assert.equal(snapshot.memberships.length,4); assert.equal(snapshot.locations.length,4);
for(const i of [2,3,4]) {await uid(i); assert.deepEqual((await rpc('get_group_recovery_snapshot',[id(100)])).locations,snapshot.locations);}
await uid(5); await assert.rejects(rpc('get_group_recovery_snapshot',[id(100)]),/not_member/);
const forbidden=event(100); assert.equal((await rpc('ingest_location_batch',[JSON.stringify([forbidden])])).rejected[0].reason,'forbidden');
await uid(1);
const fresh=event(); await rpc('ingest_location_batch',[JSON.stringify([fresh])]);
const before=(await rpc('get_group_recovery_snapshot',[id(100)])).locations;
await rpc('ingest_location_batch',[JSON.stringify([fresh])]);
assert.deepEqual((await rpc('get_group_recovery_snapshot',[id(100)])).locations,before,'duplicate must not change receipt timestamp');
const stale=event(100,Date.now()-3600000,24); const future=event(100,Date.now()+3600000,24);
const bad=event();bad.coords.latitude=100;
const result=await rpc('ingest_location_batch',[JSON.stringify([stale,future,bad])]);
assert.deepEqual(result.rejected.map(r=>r.reason),['stale_sample','invalid_event','invalid_event']);
assert.equal((await rpc('ingest_location_batch',[JSON.stringify([stale])])).rejected[0].reason,'stale_sample','rejected retry must stay rejected');
assert.equal((await rpc('ingest_location_batch',[JSON.stringify([{...fresh,coords:{...fresh.coords,latitude:24}}])])).rejected[0].reason,'invalid_event','event id cannot authenticate a changed payload');
assert.deepEqual((await rpc('get_group_recovery_snapshot',[id(100)])).locations,before);
await db.query('insert into member_privacy_settings(user_id,sharing_enabled) values($1,false)',[id(1)]);
assert.equal((await rpc('ingest_location_batch',[JSON.stringify([event()])])).rejected[0].reason,'sharing_disabled');
await uid(2); assert.equal((await rpc('get_group_recovery_snapshot',[id(100)])).locations.length,3);
const requested=await rpc('request_group_location_refresh',[id(100)]);assert.equal(requested.accepted,true);assert(requested.requested_at);assert(!requested.recipient_ids.includes(id(1)));
assert.equal((await rpc('request_group_location_refresh',[id(100)])).accepted,false);
await uid(3); const pending=(await db.query('select * from list_my_pending_location_refreshes()')).rows;
assert.equal(pending.length,1); assert.equal(await rpc('ack_my_location_refresh',[id(100),requested.requested_at]),true);
console.log('PASS: six identities, two teams, RLS isolation, snapshot convergence, idempotency, stale/future/invalid samples, privacy, cooldown, server-clock ACK');
await db.exec(`reset role;
create table public.premium_team_projections(group_id uuid primary key references public.groups(id) on delete cascade,team_premium_active boolean,source_version text,updated_at timestamptz);
create table public.personal_premium_entitlements(user_id uuid,status text,expires_at timestamptz,source text,source_version text);
create function public.group_has_active_subscription_premium(uuid) returns boolean language sql as $$ select false $$;
create function public.personal_premium_is_live(text,timestamptz) returns boolean language sql as $$ select false $$;
`);
await db.exec(read('20260929175500_premium_projection_deleted_group_guard.sql'));
assert.equal(await rpc('recompute_team_premium_projection',[id(999)]),null);
await rpc('recompute_team_premium_projection',[id(100)]);
assert.equal((await db.query('select team_premium_active from premium_team_projections where group_id=$1',[id(100)])).rows[0].team_premium_active,false);
console.log('PASS: premium projection skips deleted groups and still recomputes existing groups');
await db.close();
